# minimum number of votes
quorum: 2

# Don't count any vote from a user who votes for multiple options
prevent_doubles: true

# Required percentage of "yes" votes
threshold: 0.65

# Only process votes by contributors
contributors_only: false

# Number of days after last commit before issue can be merged
mergedelay: 3

# Number of days after last commit before issue is autoclosed
timeout: 90

locklicense: true
